- .gitignore
- Cargo.lock
- Cargo.toml
- tpke-python/.gitignore
- tpke-python/BENCHMARK.md
- tpke-python/Cargo.toml
- tpke-python/LICENSE
- tpke-python/MANIFEST.in
- tpke-python/README.md
- tpke-python/build.rs
- tpke-python/py-benches/benchmark.py
- tpke-python/pyproject.toml
- tpke-python/setup.py
- tpke-python/src/lib.rs
- tpke-python/tpke/__init__.py
- tpke-python/tpke/__init__.pyi
- tpke-wasm/BENCHMARK.md
- tpke-wasm/js-benches/index.js
- tpke-wasm/scripts/make-python-bench-inputs.js
- tpke-wasm/src/lib.rs
- tpke/BENCHMARK.md
- tpke/src/api.rs
- tpke/src/lib.rs
- Closes #2 
- Please review this PR first: https://github.com/nucypher/ferveo/pull/17
- Abstracting the code shared by WASM and Python bindings into `tpke::api`
- Adding Python benchmarks
> Python bindings and benchmark

- tpke/benches/benchmarks.rs
- tpke/src/combine.rs
- tpke/src/context.rs
- tpke/src/lib.rs
- tpke/src/refresh.rs
- Based on #20 
-  Please review parent PR first
- Already rebased
- Closes #3
- Implement share refreshing and share recovery, or "PSS" (Proactive Secret Sharing)
- For the description of share refreshing, see this [abbreviated algorithm](https://www.wikiwand.com/en/Proactive_secret_sharing#Mathematics)
- For the description of share recovery, see section 4.2 of the [PSS paper](https://link.springer.com/content/pdf/10.1007/3-540-44750-4_27.pdf) 	
- How to review this PR:
- This PR adds three tests in `tpke/src/lib.rs` that contain three different PSS flows:
- `simple_threshold_decryption_with_share_refreshing_at_point` - refreshes a key share knowing the evaluation point of a selected PSS participant
-  `simple_threshold_decryption_with_share_recovery_at_point` - recovers a key share …
> Share recovery and refreshing

- tpke/benches/tpke.rs
> Benchmarks related to Share Refresh

- ferveo/Cargo.toml
- tpke-wasm/benches/benchmarks.rs
- tpke/benches/arkworks.rs
- tpke/benches/tpke.rs
- tpke/src/combine.rs
- tpke/src/context.rs
- tpke/src/decryption.rs
- tpke/src/key_share.rs
- tpke/src/lib.rs
- Closes to #30 
- Implements a subvariant of a simple threshold decryption variant where an expensive exponentiation operation is moved from the aggregator to the decryption share creator (node). Concretely: 
- [We're calculating decryption shares](https://github.com/nucypher/ferveo/pull/32/files#diff-69e366464f9323bf110a902e9444189646025e090a9b154070b5f54437ecec7fR149), $C_{λ_i}=e(U_{λ_i},Z_i)$, where $U_{λ_i} = [λ_{i}(0)]U$
- [We're combining decryption shares](https://github.com/nucypher/ferveo/pull/32/files#diff-70820b5fd4b35ef49feefd0f6fdbbe78f758f7ac666ac7b1b61c589aa279c510R114),  $s = ∏C_{λ_i}$
- Notes for reviewers
- Notice that Lagrange coefficient computation is not a part of the benchmark. In the original simple tDec, it happens during share aggregation. In this variant, it …
> Implement a simple threshold decryption subvariant

- .github/workflows/workspace.yml
- ferveo-python/examples/server_api.py
Update ferveo example to indicate that aggregated transcript could be obtained by any side channel via deserialization.
> Update ferveo example

- .gitignore
- ferveo-python/examples/server_api.py
- ferveo-python/src/lib.rs
based on PR #75 
Exposes the following python bindings:
- `ExternalValidator.public_key`
- `ExternalValidator.address`
- `Ciphertext.__bytes__`
- `Ciphertext.from_bytes`
- `DecryptionShare.__bytes__`
- `DecryptionShare.from_bytes`
> Expose `ExternalValidator`, `DecryptionShare`, `Ciphertext` python bindings

- Cargo.lock
- ferveo-python/Cargo.toml
- ferveo-python/examples/server_api.py
- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/src/lib.rs
- ferveo/Cargo.toml
- ferveo/src/api.rs
- ferveo/src/dkg/pv.rs
- ferveo/src/lib.rs
- ferveo/src/vss/pvss.rs
- tpke-python/Cargo.toml
- tpke-wasm/src/lib.rs
- tpke/src/api.rs
- Closes #90
- Closes #89 
- Consider adding custom Python Exceptions per enum `Error` variant
- Python traceback example:
```
Traceback (most recent call last):
File "<...>/ferveo/ferveo-python/examples/server_api.py", line 108, in <module>
decrypt_with_shared_secret(ciphertext, aad, shared_secret, dkg.g1_inv)
ValueError: Ciphertext verification failed
```
> Use typed errors in user-facing APIs

- .github/workflows/workspace.yml
- Cargo.lock
- ferveo-python/Cargo.toml
- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/setup.py
- ferveo-python/src/lib.rs
- ferveo-python/test/test_ferveo.py
- ferveo-python/test/test_serialization.py
- ferveo/Cargo.toml
- ferveo/src/api.rs
- ferveo/src/lib.rs
- ferveo/src/vss/pvss.rs
- tpke-python/src/lib.rs
- tpke-wasm/Cargo.toml
- tpke-wasm/src/lib.rs
- tpke/benches/tpke.rs
- tpke/src/api.rs
- tpke/src/ciphertext.rs
- tpke/src/combine.rs
- tpke/src/context.rs
- tpke/src/decryption.rs
- tpke/src/lib.rs
- Exposes precomputed tDec variant through Python bindings
- Adds Python tests and examples
- Some renaming
- Releases `ferveo@0.1.7` on PyPi
> Support simple tDec variant in Python bindings

- ferveo/examples/bench_ark_sizes.rs
- Results:
```
| n of elements | type of element        | serialized size in bytes |
| ------------- | ---------------------- | ------------------------ |
| 1             | G1-affine-uncompressed | 104                      |
| 1             | G1-affine-compressed   | 56                       |
| 10            | G1-affine-uncompressed | 968                      |
| 10            | G1-affine-compressed   | 488                      |
| 100           | G1-affine-uncompressed | 9608                     |
| 100           | G1-affine-compressed   | 4808                     |
```
> Bench arkworks primitives sizes

- ferveo-common/src/keypair.rs
- ferveo/src/api.rs
> Expose size of `DKGPublicKey` size in bindings

- .github/workflows/workspace.yml
- Cargo.lock
- ferveo-python/Cargo.toml
- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/setup.py
- ferveo-python/src/lib.rs
- ferveo-python/test/test_ferveo.py
- ferveo-wasm/examples/node/src/main.test.ts
- ferveo-wasm/src/lib.rs
- ferveo-wasm/tests/node.rs
- ferveo/src/api.rs
- ferveo/src/lib.rs
- tpke/src/lib.rs
- Move domain points from `DkgPublicParams`  to `DecryptionShareSimple`
> Remove implicit ordering from decryption shares of simple tDec variant.

- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_ferveo.py
- ferveo-python/test/test_serialization.py
- ferveo-wasm/examples/node/src/main.test.ts
- ferveo-wasm/tests/node.rs
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- Feature
**Required reviews:**
-  1
- Removes `DkgPublicKey` from public API (bindings) and replaces it with a default value internally
- Simplifies user API
- Previously discussed [on Discord](https://discord.com/channels/411401661714792449/412681039178366996/1118171002824822925)
> Hide `DkgPublicParams` from external API

- ferveo/Cargo.toml
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- ferveo/src/lib.rs
- Bugfix
-  1
- Fixes incompatibility of `DkgPublicKey` serialized to bytes between Python and WASM bindings
- Previously added serialization method only affected Python bindings and caused incompatibility with WASM bindings
- Now downstream effect on `nucypher`
> Fix incompatible `DkgPublicKey` byte serialization

- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_ferveo.py
- ferveo/src/bindings_python.rs
- Bugfix
- 1
- Updates the definition of `ValidatorMessage` in Python bindings
- Replaces former usage in `.pyi` file, examples, etc.
- Fixes #129
- To provide correct type hints and concrete types in Python bindings
- Based on #128 
- Downstream changes addressed in https://github.com/nucypher/nucypher-core/pull/65
> Fix incorrect signatures in `.pyi` stubs 

- Cargo.lock
- ferveo-common/Cargo.toml
- ferveo-common/src/keypair.rs
- ferveo-common/src/lib.rs
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_serialization.py
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- Feature
- 2
- Implement static array serialization shortening serialized size of `FerveoPublicKey` from 104 bytes to 96 bytes
- Related to: https://github.com/nucypher/nucypher-contracts/pull/77
- Reduce the on-chain footprint of DKG participants
- Similar to previous changes to `DkgPublicKey` serialization: https://github.com/nucypher/ferveo/pull/128
> Use static arrays in `FerveoPublicKey` serialization

- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_serialization.py
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- ferveo/src/lib.rs
- Feature
- 2
- Exposes `FerveoVariant` in Python and WASM bindings
- Fixes: https://github.com/nucypher/ferveo/issues/116
- Simplifies handling of different Ferveo variants by exposing a shared type
- Based on https://github.com/nucypher/ferveo/pull/136
- Downstream changes:
- https://github.com/nucypher/nucypher/issues/3168
- https://github.com/nucypher/nucypher-ts/issues/236
> Expose `FerveoVariant` from bindings

- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo/benches/bench_main.rs
- ferveo/benches/benchmarks/eval_domain.rs
- ferveo/benches/benchmarks/mod.rs
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/dkg.rs
- ferveo/src/lib.rs
- ferveo/src/pvss.rs
- ferveo/src/utils.rs
- subproductdomain/src/lib.rs
- tpke/src/combine.rs
- tpke/src/decryption.rs
- tpke/src/lib.rs
- Feature
- 2
- Adds benchmarks to compare the performance of `MixedRadixEvaluationDomain` (without constraints on the number of coefficients) and `Radix2EvaluationDomain` (number of coefficients must be a power of two)
- Replaces usage of `Radix2EvaluationDomain` with [`GeneralEvaluationDomain`](https://docs.rs/ark-poly/latest/ark_poly/domain/general/enum.GeneralEvaluationDomain.html#) (automatically select domain size) in `ferveo`
- Fixes #130
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!
- Please see benchmarking results attached
- Based on …
> Remove powers-of-2 restriction on cohort size

- README.md
- ferveo-common/src/lib.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- rust-toolchain.toml
- tpke/benches/tpke.rs
- tpke/src/ciphertext.rs
- tpke/src/context.rs
- tpke/src/decryption.rs
Some of the changes introduced by this PR, all of them related with how ciphertexts are produced and used:
* Actually use the AAD input of the AEAD API of Chacha20Poly1305
* Closes #146 
* Decouple the bulk of symmetric ciphertext from validation; instead just use the hash. This allows to have a small (and also constant!) decryption request. 
* Closes #147 
* Implies changes in nucypher-core and nucypher (TBD)
* Refactor `Ciphertext` implementation.
* Fixes #144 
* Remove unused & incorrect ciphertext length method (see #145 )
Apart from this, bumps MSRV to 1.67.0, and associated clippy changes.
@jMyles and @KPrasch identified an important limitation of current ciphertexts and TDec requests construction. …
> Revamping Ferveo Ciphertexts (breaking changes ⚠️ )

- README.md
- ferveo-common/src/lib.rs
- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_ferveo.py
- ferveo-wasm/examples/node/src/main.test.ts
- ferveo-wasm/tests/node.rs
- ferveo/benches/benchmarks/validity_checks.rs
- ferveo/examples/bench_ark_sizes.rs
- ferveo/examples/bench_primitives_size.rs
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- ferveo/src/dkg.rs
- ferveo/src/lib.rs
- ferveo/src/pvss.rs
- rust-toolchain.toml
- tpke/benches/tpke.rs
- tpke/src/api.rs
- tpke/src/ciphertext.rs
- tpke/src/context.rs
- tpke/src/decryption.rs
- tpke/src/lib.rs
- Feature
- 2
- Exposes `Ciphertext.header -> CiphertextHeader` and `Ciphertext.payload -> bytes` from Python bindings
- #154
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!
- TODO: Only merge after testing these changes in the downstream
- TODO: Make sure to also update `nucypher-core` stub files, `*.pyi`, upon updating
- Based on https://github.com/nucypher/ferveo/pull/149 - Please review & merge it first
- There's only one commit to review here: https://github.com/nucypher/ferveo/pull/155/commits/1800d3c5db164947c7cae35433fb8e3ad2650b66
- Who is using …
> Update `Ciphertext` bindings

- README.md
- ferveo-common/src/lib.rs
- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/ferveo/__init__.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_ferveo.py
- ferveo-wasm/examples/node/src/main.test.ts
- ferveo-wasm/tests/node.rs
- ferveo/benches/benchmarks/validity_checks.rs
- ferveo/examples/bench_ark_sizes.rs
- ferveo/examples/bench_primitives_size.rs
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- ferveo/src/dkg.rs
- ferveo/src/lib.rs
- ferveo/src/pvss.rs
- rust-toolchain.toml
- tpke/benches/tpke.rs
- tpke/src/api.rs
- tpke/src/ciphertext.rs
- tpke/src/context.rs
- tpke/src/decryption.rs
- tpke/src/lib.rs
> How many reviews does the PR author need?
Based over #155 (which is based over #149 )
Related to:
- https://github.com/nucypher/nucypher-core/pull/74
- https://github.com/nucypher/nucypher/pull/3194.
> - Fixes #...
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?
> Changes needed for ACP, ThresholdMessageKit work in `nucypher-core`

- .github/workflows/workspace.yml
- ferveo/src/pvss.rs
- Other
- 1
- Installs `wasm-pack` from a precompiled binary
- Fixes a listing issue on Rust `stable`
- Some child dependencies in `wasm-pack` an `wasm-opt` get updated from time to time and that causes MSRV float
- With these changes, we should be able to avoid that in the future, and hence avoid CI breaking from time to time
> Fix CI build

- ferveo/Cargo.toml
- ferveo/src/dkg.rs
- ferveo/src/lib.rs
- ferveo/src/pvss.rs
- ferveo/src/refresh.rs
- tpke/benches/arkworks.rs
- tpke/benches/tpke.rs
- tpke/src/combine.rs
- tpke/src/decryption.rs
- tpke/src/lib.rs
This PR is mainly a refactor of code related to refresh & recovery procedures. The main contributions are:
* Relocation of refresh & recovery code from the `tpke` crate to the `ferveo` crate
* Fixing incorrect refresh & recovery tests (see e.g., 8ef9e7ff809af400808dbbc750d2afa25a7cde53)
* General improvements in tests
* Closes #73 
This work is the basis to implementing the recovery & refresh protocols (see #163)
No breaking changes!
Work in this PR has surfaced these issues:
* #160 
* #161
* #162
* #163
> Refactor of Refresh & Recovery procedures

- Cargo.lock
- ferveo-tdec/benches/tpke.rs
- ferveo-tdec/src/context.rs
- ferveo-tdec/src/lib.rs
- ferveo-wasm/examples/node/src/main.test.ts
- ferveo-wasm/tests/node.rs
- ferveo/Cargo.toml
- ferveo/benches/benchmarks/block_proposer.rs
- ferveo/benches/benchmarks/mod.rs
- ferveo/benches/benchmarks/validity_checks.rs
- ferveo/examples/bench_primitives_size.rs
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- ferveo/src/dkg.rs
- ferveo/src/lib.rs
- ferveo/src/pvss.rs
- ferveo/src/refresh.rs
- ferveo/src/test_common.rs
- ferveo/src/validator.rs
- Refactor
- 1
- Refactors DKG parameters usage and validation into `DkgParams`
- Uses `test_case` crate in tests to duplicate test scenarios
- Refactors shared test utils and variables into `ferveo::test_common` module
- Replaces some panics with proper error handling and error types
- Fixes some outstanding TODOs
- This PR contains no API changes. I opted to address these changes here to avoid bundling them with PRs that contain functional changes, making it easier to review them. 
- Reviewing commit by commit should be easier
- Based on https://github.com/nucypher/ferveo/pull/166 - Please review it first
> Refactor DKG parameters into a `DkgParams`

- ferveo/src/api.rs
- ferveo/src/dkg.rs
- Other
- 1
- Documents deterministic behavior of domain points. 
- Determinism is based on the generator derived from rounding selected domain size. As long as the domain size remains the same, so does the generator. Hence, for certain sizes of the domain, the domain points generated are deterministic
- The domain size is based on the `validators_num` parameter of the DKG. `validators_num` is rounded up to the nearest power of two. So as long as our `validators_num` is rounded to the same domain size size as `validators_num` of a different DKG instance, our domain points are the same. 
- See tests for examples of that behavior
> - Fixes #...
> Explain how this PR fits in the greater …
> Document domain points determinism in DKG instances

- ferveo-python/examples/server_api_precomputed.py
- ferveo-python/examples/server_api_simple.py
- ferveo-python/ferveo/__init__.pyi
- ferveo-python/test/test_ferveo.py
- ferveo-tdec/benches/tpke.rs
- ferveo-tdec/src/context.rs
- ferveo-tdec/src/decryption.rs
- ferveo-tdec/src/lib.rs
- ferveo-wasm/examples/node/src/main.test.ts
- ferveo-wasm/tests/node.rs
- ferveo/src/api.rs
- ferveo/src/bindings_python.rs
- ferveo/src/bindings_wasm.rs
- ferveo/src/dkg.rs
- ferveo/src/lib.rs
- ferveo/src/pvss.rs
- ferveo/src/refresh.rs
- ferveo/src/test_common.rs
- Bugfix
-  Feature
- 1
> High-level idea of the changes introduced in this PR. 
> List relevant API changes (if any), as well as related PRs and issues.
- Fixes #179
- Fixes #184 
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!
- Based on #183 - Please review it first
- I will review these changes myself again after merging parent PR
> Create an aggregate from subset of messages

- Cargo.lock
- Cargo.toml
- ferveo-common/Cargo.toml
- ferveo-python/Cargo.toml
- ferveo-tdec/Cargo.toml
- ferveo-wasm/Cargo.toml
- ferveo/Cargo.toml
- subproductdomain/Cargo.toml
- Other
- 1
- Deduplicates where needed and moves dependencies to `./Cargo.toml`
- Generated with [`cargo autoinherit`](https://mainmatter.com/blog/2024/03/18/cargo-autoinherit/)
- Prevents conflicting child dependency version, a source of confusion when debugging conflicts with `cargo tree`
> Move shared dependencies to the workspace crate
